### ISSUE TITLE
Страница "вендор"

### ISSUE THREAD

**Issue by Segr** [perchick/csoft-website-1.0.2#10]
Пример текущей страницы - https://www.csoft.ru/about/vendors/csoft-development.html

Информация которую надо показать
- название
- логотип вендора
- "партнерский текст"
![image](https://user-images.githubusercontent.com/3256443/142763860-69ac0660-1bcf-40ba-b58a-cae797506b27.png)
- описание вендора
- официальный сайт
- текст 
- список программных продуктов от этого вендора (название, картинка, краткое описание)
- новости по этому вендору
- мероприятия по этому вендору
- акции по этому вендору

**Comment by aperekrestov** [comment]
Добавил страницу вендора: http://perekrestov.ru/gk-csoft/vendor-page.html
