### ISSUE TITLE
Переименовать города на карте

### ISSUE THREAD

**Issue by Segr** [perchick/csoft-website-1.0.2#13]
Для совместимости скриптов с внутренними именами объектов надо переименовать.

moscow -> moskva
nizhny-novgorod -> nizhnij-novgorod
petersburg -> sankt-peterburg
khabarovsk -> habarovsk

подправленный _#src-code\map.html_
[map.html.txt](https://github.com/perchick/csoft-website-1.0.2/files/7576924/map.html.txt)

подправленный _#src-code\js\map.js_
[map.js.txt](https://github.com/perchick/csoft-website-1.0.2/files/7576931/map.js.txt)

**Comment by aperekrestov** [comment]
Скрипты обновил, спасибо за подправленные файлы!
Ссылка на страницу: http://perekrestov.ru/gk-csoft/contacts.html
