### ISSUE TITLE
Багофича в меню

### ISSUE THREAD

**Issue by Segr** [perchick/csoft-website-1.0.2#15]
Ссылки с анкорами не открываются, если находишься на той же странице.

Воспроизвести
- открыть страницу "о компании"
- открыть меню
- попытаться кликнуть на ссылку  с анкором на текущую страницу
ничего не происходит, браузер не обновляет страницу, если ссылка идет на анкор внутри неё, он просто скролит её, а меню не закрывается.

**Comment by aperekrestov** [comment]
Давай решим эту проблему абсолютной ссылкой, в таком случае баговича исчезнет. Это простой способ. 

Более сложный способ – написать и добавить скрипт, который будет отслеживать переход на якорную ссылку и закрывать меню.
