### ISSUE TITLE
правки и ссылки

### ISSUE THREAD

**Issue by Segr** [perchick/csoft-website-1.0.2#2]
ссылка на habr - https://habr.com/ru/users/CSoft/posts/

ссылка на csoft - https://www.youtube.com/channel/UCZT31jFF-KG4ihMgyFbFB6g

копирайт  - © CSoft 2002−2021

в меню анкоры во множественном числе, а на страницах, например "о компании" в единственном

**Comment by aperekrestov** [comment]
Ссылочки добавил, копирайт обновил. Про анкоры не совсем понял, кнопка "о компании" - ссылка "about.html", что где поправить напиши поподробнее

**Comment by Segr** [comment]
Про анкоры перефразирую.
Если блок содержит в себе несколько продуктов, то правильный анкор - #products.
(я видимо где-то  у себя правил при переносе верстки, и потому у меня так получилось.
Но если все анкоры будут исправлены на множественные числа, если они ведут на блоки с множеством объектов - это будет правильно.
