### ISSUE TITLE
создать общую страницу "Проекты"

### ISSUE THREAD

**Issue by Segr** [perchick/csoft-website-1.0.2#3]
На сайте присутствуют блоки проектов и решений.
Нужно сделать страницу проектов - projects.html, а оттуда ссылки на project-page.html

Так же просмотреть все блоки чтобы с проектов были ссылки на проекты, а с решений на решения.

**Comment by aperekrestov** [comment]
Сделано
solutions.html -> solution-page.html
projects.html -> solution-page.html
