### ISSUE TITLE
policy & agreement

### ISSUE THREAD

**Issue by Segr** [perchick/csoft-website-1.0.2#4]
На сайте должны быть две страницы юридических.
Пользовательское Соглашение -> agreement.html (нужно создать, текст тут https://try.csoft.ru/info/agreement.html, но это я наверное криво накидал)
Политика конфиденциальности -> policy

Ссылки на эти страницы должны быть явно доступны в любом месте сайта, можно в виде текста, можно с иконок. Наверное это в подвале лучше сделать.

**Comment by aperekrestov** [comment]
Добавил, залил на гит, обновляю ссылку превью
