### ISSUE TITLE
Шапка у страницы "машиностроение"

### ISSUE THREAD

**Issue by Segr** [perchick/csoft-website-1.0.2#7]
Тексты должны быть выровнены, знак ">" в столбцах должен быть в один столбец.
А подписи под цифрами должны быть выровнены по цифре.

![image](https://user-images.githubusercontent.com/3256443/142763202-b658a90c-a63b-4276-b9a0-df50462ba834.png)

**Comment by aperekrestov** [comment]
Обновил верстку инфографики
