### ISSUE TITLE
Страница "Вендоры"

### ISSUE THREAD

**Issue by Segr** [perchick/csoft-website-1.0.2#9]
Нужно сделать страницу вендоров - vendors.html

Текущая страница - https://www.csoft.ru/about/vendors/
Страница собранная из доступных блоков - https://try.csoft.ru/about/vendors.html

Надо блок слайдера вендоров развернуть, чтобы все вендоры были доступны сразу, желательно чтобы описательный текст для вендора был доступен.

С каждой иконки ссылка на vendor-page.html

**Comment by aperekrestov** [comment]
Добавил страницу и ссылки
